Repository pyxem/pyxem, pull requests merged in 2018-10, with the labels that each got.

#281 update docstrings *args, **kwargs in electron_diffraction
  pyxem/signals/electron_diffraction.py
  pyxem/utils/expt_utils.py
Labels: documentation

#278 A Cross Correlation based peak finder
  pyxem/signals/electron_diffraction.py
  pyxem/utils/peakfinders2D.py
  tests/test_signals/test_electron_diffraction.py
  tests/test_utils/test_peakfinders2D.py
Labels: status: WIP

#289 Transfer axes between classes related by functions/generators
  pyxem/generators/diffraction_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/generators/library_generator.py
  pyxem/generators/vdf_generator.py
  pyxem/libraries/structure_library.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction_simulation.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/electron_diffraction.py
  tests/test_generators/test_library_generator.py
  tests/test_library/test_diffraction_library.py
  tests/test_signals/test_diffraction_vectors.py
Labels: enhancement, status: WIP

#305 Masks for the radial average function.
  pyxem/signals/electron_diffraction.py
  pyxem/utils/expt_utils.py
  tests/test_signals/test_electron_diffraction.py
Labels: enhancement

#293 Tidying up and checking crystallographic mapping workflow
  pyxem/__init__.py
  pyxem/generators/indexation_generator.py
  pyxem/io_plugins/mib.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/indexation_results.py
  pyxem/utils/expt_utils.py
  pyxem/utils/sim_utils.py
  requirements.txt
  tests/test_physical/test_orientation_mapping_nonphys.py
  tests/test_signals/test_crystallographic_map.py
Labels: documentation, enhancement
