Repository pyxem/pyxem, pull requests merged in 2018-08, with the labels that each got.

#201 New VDFGenerator
  pyxem/generators/vdf_generator.py
  pyxem/signals/diffraction_vectors.py
  pyxem/utils/expt_utils.py
  tests/test_utils/test_expt_utils.py
  tests/test_utils/test_sim_utils.py
Labels: enhancement, status: WIP

#204 Testing DiffractionVectors and VDFGenerator methods
  docs/source/images/axis_conventions_pyxem.png
  docs/source/images/axis_conventions_pyxem.svg
  pyxem/utils/expt_utils.py
  tests/test_generators/test_vdf_generator.py
  tests/test_signals/test_diffraction_vectors.py
  tests/test_utils/test_expt_utils.py
Labels: enhancement, status: WIP

#207 Refactoring tests
  pyxem/signals/crystallographic_map.py
  pyxem/signals/electron_diffraction.py
  pyxem/utils/expt_utils.py
  setup.py
  src/build.bat
  src/radialprofile.pyx
  src/setup.py
  tests/test_signals/test_crystallographic_map.py
  tests/test_signals/test_electron_diffraction.py
Labels: status: WIP

#212 Test DiffractionProfile indexation methods
  pyxem/generators/diffraction_generator.py
  pyxem/generators/indexation_generator.py
  tests/test_generators/test_diffraction_generator.py
  tests/test_generators/test_indexation_generator.py
  tests/test_signals/test_diffraction_profile.py
  tests/test_signals/test_diffraction_simulation.py
Labels: enhancement, status: WIP

#222 Test plotting
  pyxem/signals/diffraction_simulation.py
  pyxem/signals/diffraction_vectors.py
  tests/test_signals/test_diffraction_simulation.py
  tests/test_signals/test_diffraction_vectors.py
Labels: enhancement, status: WIP

#220 Peak finding improvements, including ragged array tidying up
  pyxem/utils/expt_utils.py
  pyxem/utils/peakfinders2D.py
  tests/test_signals/test_electron_diffraction.py
Labels: status: WIP

#223 Testing
  pyxem/generators/diffraction_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/signals/diffraction_vectors.py
  pyxem/utils/sim_utils.py
  tests/test_components/test_scalable_reference_pattern.py
  tests/test_generators/test_diffraction_generator.py
  tests/test_generators/test_vdf_generator.py
  tests/test_orientation_mapping_phys.py
  tests/test_signals/test_diffraction_simulation.py
  tests/test_signals/test_diffraction_vectors.py
  tests/test_strain_mapping.py
  tests/test_utils/test_sim_utils.py
Labels: enhancement
