Repository pyxem/pyxem, pull requests merged in 2018-09, with the labels that each got.

#252 VDFGenerator enhancements
  pyxem/generators/vdf_generator.py
  tests/test_generators/test_vdf_generator.py
Labels: enhancement, status: WIP

#258 Bugfixes and minor addition for the orientation mapping workflow
  pyxem/utils/sim_utils.py
Labels: status: WIP

#259 Documentation Improvements
  README.rst
Labels: documentation
