Repository pyxem/pyxem, pull requests merged in 2019-09, with the labels that each got.

#464 Lock numpy version to 1.16.5 due to hyperspy bug with 1.17.0
  setup.py
Labels: bug, dev

#460 Add integration generator [WIP]
  pyxem/generators/generator_utils.py
  pyxem/generators/integration_generator.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/signals/diffraction_vectors.py
  pyxem/tests/test_generators/test_integration_generator.py
Labels: enhancement, status: WIP

#468 Implement orientation refinement routine
  .travis.yml
  appveyor.yml
  pyxem/generators/indexation_generator.py
  pyxem/signals/indexation_results.py
  pyxem/tests/conftest.py
  pyxem/tests/test_generators/test_indexation_generator.py
  pyxem/tests/test_physical/test_orientation_mapping_phys.py
  pyxem/tests/test_signals/test_indexation_results.py
  pyxem/tests/test_utils/test_indexation_utils.py
  pyxem/utils/indexation_utils.py
  setup.py
Labels: enhancement, status: WIP

#450 Add clustering to get_unique_vectors()
  pyxem/signals/diffraction_vectors.py
  pyxem/tests/test_signals/test_diffraction_vectors.py
  pyxem/utils/vector_utils.py
Labels: enhancement, status: WIP

#472 Load mib
  .coveragerc
  pyxem/io_plugins/__init__.py
  pyxem/io_plugins/mib.py
  pyxem/utils/io_utils.py
Labels: enhancement, status: WIP

#409 register as hyperspy extension
  pyxem/hyperspy_extension.yaml
  setup.py
Labels: dev, status: WIP

#474 ePDF and FEM analysis
  pyxem/__init__.py
  pyxem/components/reduced_intensity_correction_component.py
  pyxem/components/scattering_fit_component_lobato.py
  pyxem/components/scattering_fit_component_xtables.py
  pyxem/generators/pdf_generator1d.py
  pyxem/generators/red_intensity_generator1d.py
  pyxem/generators/variance_generator.py
  pyxem/hyperspy_extension.yaml
  pyxem/signals/diffraction_variance1d.py
  pyxem/signals/diffraction_variance2d.py
  pyxem/signals/pair_distribution_function1d.py
  pyxem/signals/reduced_intensity1d.py
  pyxem/tests/test_components/test_red_int_correction_component.py
  pyxem/tests/test_components/test_scattering_fit_component_lobato.py
  pyxem/tests/test_components/test_scattering_fit_component_xtables.py
  pyxem/tests/test_generators/test_pdf_generator.py
  pyxem/tests/test_generators/test_red_intensity_generator.py
  pyxem/tests/test_generators/test_variance_generator.py
  pyxem/tests/test_signals/test_diffraction_variance1d.py
  pyxem/tests/test_signals/test_diffraction_variance2d.py
  pyxem/tests/test_signals/test_pdf1d.py
  pyxem/tests/test_signals/test_reduced_intensity1d.py
  pyxem/utils/expt_utils.py
  pyxem/utils/pdf_utils.py
  pyxem/utils/ri_utils.py
Labels: enhancement, status: WIP

#488 update __init__.py to have correct info
  pyxem/__init__.py
  pyxem/release_info.py
  pyxem/version.py
  setup.py
Labels: bug, dev
