Repository pyxem/pyxem, pull requests merged in 2019-06, with the labels that each got.

#417 Setting an explicit matplotlib backend
  .travis.yml
  pyxem/tests/test_physical/test_orientation_mapping_nonphys.py
Labels: will-need-backport

#419 Pepstorm code cleanup
  pyxem/generators/calibration_generator.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/libraries/calibration_library.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/electron_diffraction.py
  pyxem/tests/test_generators/test_calibration_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_library/test_calibration_library.py
  pyxem/tests/test_library/test_diffraction_library.py
  pyxem/tests/test_physical/test_orientation_mapping_nonphys.py
  pyxem/tests/test_signals/test_electron_diffraction.py
  pyxem/tests/test_utils/test_calibration_utils.py
  pyxem/utils/calibration_utils.py
  pyxem/utils/expt_utils.py
  pyxem/utils/sim_utils.py
  setup.py
Labels: dev

#424 Import roi from hyperspy
  pyxem/__init__.py
  pyxem/tests/test_signals/test_electron_diffraction.py
Labels: bug
