Repository pyxem/pyxem, pull requests merged in 2019-10, with the labels that each got.

#494 Improve subpixel generator testing
  pyxem/tests/test_generators/test_displacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_physical/test_marker_plotting.py
Labels: status: WIP

#506 pepstorm pep8 corrections
  pyxem/generators/calibration_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/generators/pdf_generator1d.py
  pyxem/generators/red_intensity_generator1d.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/generators/variance_generator.py
  pyxem/libraries/calibration_library.py
  pyxem/signals/__init__.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/pair_distribution_function1d.py
  pyxem/signals/reduced_intensity1d.py
  pyxem/signals/tensor_field.py
  pyxem/tests/test_generators/test_displacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/tests/test_utils/test_subpixel_utils.py
  pyxem/utils/expt_utils.py
  pyxem/utils/indexation_utils.py
  pyxem/utils/io_utils.py
  pyxem/utils/pdf_utils.py
  pyxem/utils/peakfinders2D.py
  pyxem/utils/ri_utils.py
  pyxem/utils/subpixel_refinements_utils.py
Labels: dev, enhancement

#503 pyFAI Integration
  .travis.yml
  appveyor.yml
  pyxem/detectors/__init__.py
  pyxem/detectors/generic_flat_detector.py
  pyxem/detectors/medipix_256x256.py
  pyxem/detectors/medipix_515x515.py
  pyxem/signals/diffraction2d.py
  pyxem/tests/test_detectors/__init__.py
  pyxem/tests/test_detectors/test_generic_flat_detector.py
  pyxem/tests/test_detectors/test_medipix_256x256.py
  pyxem/tests/test_detectors/test_medipix_515x515.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/utils/expt_utils.py
  setup.py
Labels: enhancement, status: WIP
