Repository pyxem/pyxem, pull requests merged in 2019-07, with the labels that each got.

#427 Improving the Loading Function
  pyxem/__init__.py
  pyxem/signals/__init__.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction_profile.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/electron_diffraction.py
  pyxem/signals/indexation_results.py
  pyxem/signals/vdf_image.py
  pyxem/tests/test__init__.py
  pyxem/tests/test_utils/test_io_utils.py
  pyxem/utils/io_utils.py
Labels: enhancement

#430 Class restructuring
  pyxem/__init__.py
  pyxem/generators/calibration_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/generators/vdf_generator.py
  pyxem/libraries/calibration_library.py
  pyxem/signals/__init__.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction1d.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/diffraction_simulation.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/electron_diffraction1d.py
  pyxem/signals/electron_diffraction2d.py
  pyxem/signals/indexation_results.py
  pyxem/signals/vdf_image.py
  pyxem/tests/conftest.py
  pyxem/tests/test_components/test_scalable_reference_pattern.py
  pyxem/tests/test_generators/test_calibration_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_generators/test_vdf_generator.py
  pyxem/tests/test_library/test_calibration_library.py
  pyxem/tests/test_physical/test_marker_plotting.py
  pyxem/tests/test_physical/test_orientation_mapping_nonphys.py
  pyxem/tests/test_physical/test_orientation_mapping_phys.py
  pyxem/tests/test_physical/test_strain_mapping.py
  pyxem/tests/test_signals/test_diffraction1d.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_diffraction_profile.py
  pyxem/tests/test_signals/test_diffraction_simulation.py
  pyxem/tests/test_signals/test_electron_diffraction1d.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/tests/test_utils/test_calibration_utils.py
  pyxem/tests/test_utils/test_expt_utils.py
  pyxem/tests/test_utils/test_io_utils.py
  pyxem/tests/test_utils/test_sim_utils.py
  pyxem/utils/expt_utils.py
  pyxem/utils/io_utils.py
  pyxem/utils/sim_utils.py
  pyxem/utils/vector_utils.py
Labels: dev, enhancement

#435 add default values to plot_diffraction_vectors
  pyxem/signals/diffraction_vectors.py
Labels: enhancement

#437 Updating install requirements for v0.9.0
  setup.py
Labels: dev

#429 Factor out simulation code to diffsims
  .travis.yml
  appveyor.yml
  pyxem/__init__.py
  pyxem/generators/diffraction_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/generators/library_generator.py
  pyxem/generators/structure_library_generator.py
  pyxem/libraries/diffraction_library.py
  pyxem/libraries/structure_library.py
  pyxem/libraries/vector_library.py
  pyxem/signals/__init__.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction_simulation.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/indexation_results.py
  pyxem/tests/conftest.py
  pyxem/tests/test_components/test_diffraction_component.py
  pyxem/tests/test_generators/test_diffraction_generator.py
  pyxem/tests/test_generators/test_indexation_generator.py
  pyxem/tests/test_generators/test_library_generator.py
  pyxem/tests/test_generators/test_structure_library_generator.py
  pyxem/tests/test_library/test_diffraction_library.py
  pyxem/tests/test_library/test_structure_library.py
  pyxem/tests/test_library/test_vector_library.py
  pyxem/tests/test_physical/test_marker_plotting.py
  pyxem/tests/test_physical/test_orientation_mapping_nonphys.py
  pyxem/tests/test_physical/test_orientation_mapping_phys.py
  pyxem/tests/test_physical/test_strain_mapping.py
  pyxem/tests/test_signals/test_diffraction_simulation.py
  pyxem/tests/test_utils/test_sim_utils.py
  pyxem/utils/atomic_scattering_params.py
  pyxem/utils/indexation_utils.py
  pyxem/utils/io_utils.py
  pyxem/utils/lobato_scattering_params.py
  pyxem/utils/scattering_params.py
  pyxem/utils/sim_utils.py
  setup.py
Labels: dev, enhancement, status: WIP

#438 Bugfix for local Gaussian Subpixelrefinement
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
Labels: bug

#425 Introduce least squares method for strain mapping
  pyxem/generators/displacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_displacement_gradient_tensor_generator.py
Labels: enhancement

#441 Decomposition wrapper
  pyxem/signals/diffraction1d.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/electron_diffraction1d.py
  pyxem/signals/electron_diffraction2d.py
  pyxem/tests/test_signals/test_diffraction1d.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_electron_diffraction1d.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/tests/test_signals/test_lazy_diffraction1d.py
  pyxem/tests/test_signals/test_lazy_diffraction2d.py
  pyxem/tests/test_signals/test_lazy_electron_diffraction1d.py
  pyxem/tests/test_signals/test_lazy_electron_diffraction2d.py
Labels: bug

#418 Rotation calibration
  README.rst
  pyxem/generators/calibration_generator.py
  pyxem/libraries/calibration_library.py
  pyxem/tests/test_generators/test_calibration_generator.py
  pyxem/tests/test_library/test_calibration_library.py
  pyxem/version.py
Labels: enhancement, status: WIP

#444 Start release cycle 0.10.0
  pepstorm.sh
  pyxem/generators/calibration_generator.py
  pyxem/generators/displacement_gradient_tensor_generator.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/io_plugins/__init__.py
  pyxem/io_plugins/mib.py
  pyxem/tests/test_generators/test_calibration_generator.py
  pyxem/tests/test_generators/test_displacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_physical/test_orientation_mapping_nonphys.py
  pyxem/tests/test_physical/test_strain_mapping.py
  pyxem/utils/indexation_utils.py
  pyxem/utils/io_utils.py
  pyxem/utils/peakfinders2D.py
  pyxem/version.py
Labels: dev
