Repository pyxem/pyxem, pull requests merged in 2019-04, with the labels that each got.

#361 refactor apply affine transformation - improves speed
  pyxem/signals/electron_diffraction.py
  pyxem/utils/expt_utils.py
Labels: enhancement

#355 Add windows and macos testing
  .travis.yml
  README.rst
  appveyor.yml
Labels: bug

#364 Package tests
  pyxem/tests/__init__.py
  pyxem/tests/conftest.py
  pyxem/tests/test_components/__init__.py
  pyxem/tests/test_components/test_diffraction_component.py
  pyxem/tests/test_components/test_scalable_reference_pattern.py
  pyxem/tests/test_generators/__init__.py
  pyxem/tests/test_generators/test_diffraction_generator.py
  pyxem/tests/test_generators/test_diplacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_indexation_generator.py
  pyxem/tests/test_generators/test_library_generator.py
  pyxem/tests/test_generators/test_structure_library_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_generators/test_vdf_generator.py
  pyxem/tests/test_library/__init__.py
  pyxem/tests/test_library/test_diffraction_library.py
  pyxem/tests/test_library/test_vector_library.py
  pyxem/tests/test_physical/__init__.py
  pyxem/tests/test_physical/test_marker_plotting.py
  pyxem/tests/test_physical/test_orientation_mapping_nonphys.py
  pyxem/tests/test_physical/test_orientation_mapping_phys.py
  pyxem/tests/test_physical/test_strain_mapping.py
  pyxem/tests/test_signals/__init__.py
  pyxem/tests/test_signals/test_crystallographic_map.py
  pyxem/tests/test_signals/test_diffraction_profile.py
  pyxem/tests/test_signals/test_diffraction_simulation.py
  pyxem/tests/test_signals/test_diffraction_vectors.py
  pyxem/tests/test_signals/test_electron_diffraction.py
  pyxem/tests/test_signals/test_indexation_results.py
  pyxem/tests/test_signals/test_tensor_field.py
  pyxem/tests/test_utils/__init__.py
  pyxem/tests/test_utils/test_expt_utils.py
  pyxem/tests/test_utils/test_indexation_utils.py
  pyxem/tests/test_utils/test_peakfinders2D.py
  pyxem/tests/test_utils/test_sim_utils.py
  pyxem/tests/test_utils/test_subpixel_utils.py
  pyxem/tests/test_utils/test_vector_utils.py
  setup.py
Labels: enhancement

#365 Fix or remove code breaking tests
  docs/source/contents.rst
  docs/source/literature.rst
  pyxem/__init__.py
  pyxem/generators/displacement_gradient_tensor_generator.py
  pyxem/signals/electron_diffraction.py
  pyxem/tests/test_signals/test_electron_diffraction.py
  pyxem/tests/test_utils/test_expt_utils.py
  pyxem/utils/expt_utils.py
  pyxem/utils/peakfinders2D.py
Labels: bug

#363 add interactive vdf function for ElectronDiffractionProfile
  pyxem/signals/diffraction_profile.py
  pyxem/signals/electron_diffraction.py
  pyxem/tests/conftest.py
  pyxem/tests/test_signals/test_diffraction_profile.py
Labels: enhancement, status: WIP

#368 Bugfix for the an x-y confusion within our strain mapping
  pyxem/generators/displacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_diplacement_gradient_tensor_generator.py
  pyxem/tests/test_generators/test_displacement_gradient_tensor_generator.py
Labels: bug

#372 Return code-coverage to 100%
  pyxem/tests/test_components/test_scalable_reference_pattern.py
  pyxem/tests/test_signals/test_crystallographic_map.py
  pyxem/tests/test_signals/test_diffraction_simulation.py
  pyxem/tests/test_utils/test_sim_utils.py
Labels: bug

#374 BUGFIX: Forcing spg to take sensible (with diffraction pattern) vectors
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
Labels: enhancement

#376 Fix docstrings
  docs/source/index.rst
  pyxem/generators/displacement_gradient_tensor_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/io_plugins/mib.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/electron_diffraction.py
  pyxem/signals/indexation_results.py
  pyxem/utils/indexation_utils.py
Labels: documentation
