Repository pyxem/pyxem, pull requests merged in 2019-05, with the labels that each got.

#390 Vector match improvements
  pyxem/generators/indexation_generator.py
  pyxem/generators/library_generator.py
  pyxem/libraries/structure_library.py
  pyxem/libraries/vector_library.py
  pyxem/signals/crystallographic_map.py
  pyxem/tests/conftest.py
  pyxem/tests/test_generators/test_indexation_generator.py
  pyxem/tests/test_generators/test_structure_library_generator.py
  pyxem/tests/test_library/test_structure_library.py
  pyxem/tests/test_library/test_vector_library.py
  pyxem/tests/test_physical/test_orientation_mapping_phys.py
  pyxem/tests/test_signals/test_crystallographic_map.py
  pyxem/tests/test_utils/test_indexation_utils.py
  pyxem/utils/indexation_utils.py
Labels: bug, enhancement

#391 add axis flip to load_mib
  pyxem/__init__.py
Labels: bug

#401 Fix vector library generator
  pyxem/generators/library_generator.py
  pyxem/tests/test_utils/test_indexation_utils.py
  pyxem/tests/test_utils/test_vector_utils.py
  pyxem/utils/indexation_utils.py
  pyxem/utils/sim_utils.py
  pyxem/utils/vector_utils.py
Labels: bug, enhancement

#403 Starting 0.9.0
  .travis.yml
  PULL_REQUEST_TEMPLATE.md
  appveyor.yml
  pyxem/version.py
  setup.py
Labels: dev
