Repository pyxem/pyxem, pull requests merged in 2020-03, with the labels that each got.

#549 Updating load_mib
  pyxem/utils/io_utils.py
Labels: enhancement

#553 Fix signal registration
  pyxem/__init__.py
  pyxem/generators/indexation_generator.py
  pyxem/generators/integration_generator.py
  pyxem/generators/pdf_generator1d.py
  pyxem/generators/red_intensity_generator1d.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/hyperspy_extension.yaml
  pyxem/signals/__init__.py
  pyxem/signals/crystallographic_map.py
  pyxem/signals/diffraction1d.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/diffraction_variance1d.py
  pyxem/signals/diffraction_variance2d.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/electron_diffraction1d.py
  pyxem/signals/electron_diffraction2d.py
  pyxem/signals/indexation_results.py
  pyxem/signals/pair_distribution_function1d.py
  pyxem/signals/reduced_intensity1d.py
  pyxem/signals/segments.py
  pyxem/signals/strain_map.py
  pyxem/signals/tensor_field.py
  pyxem/signals/vdf_image.py
  pyxem/tests/test_signals/test_diffraction1d.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_diffraction_variance2d.py
  pyxem/tests/test_signals/test_diffraction_vectors.py
  pyxem/tests/test_signals/test_electron_diffraction1d.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/tests/test_utils/test_expt_utils.py
  pyxem/tests/test_utils/test_io_utils.py
  pyxem/utils/io_utils.py
Labels: dev

#558 Generalising get_diffraction_calibration to any detector size
  pyxem/generators/calibration_generator.py
Labels: bug, easy_fix, enhancement

#561 black style in calibration_generator
  pyxem/generators/calibration_generator.py
Labels: dev

#566 add black style badge
  README.rst
Labels: documentation

#567 Generalising reference_circle in calibration_generator
  pyxem/generators/calibration_generator.py
Labels: enhancement

#570 Tweak test suite
  pyxem/tests/conftest.py
  pyxem/tests/test_utils/test_big_data_utils.py
  pyxem/utils/big_data_utils.py
Labels: dev

#564 Improvements to DiffractionVectors
  pyxem/signals/diffraction_vectors.py
  pyxem/tests/test_signals/test_diffraction_vectors.py
Labels: bug, dev, enhancement

#565 Improve virtual image
  pyxem/signals/common_diffraction.py
  pyxem/signals/diffraction1d.py
  pyxem/signals/diffraction2d.py
  pyxem/tests/test_signals/test_diffraction1d.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_electron_diffraction1d.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
Labels: enhancement

#524 Polar reprojection
  pyxem/__init__.py
  pyxem/generators/calibration_generator.py
  pyxem/hyperspy_extension.yaml
  pyxem/signals/common_diffraction.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/electron_diffraction2d.py
  pyxem/signals/polar_diffraction2d.py
  pyxem/tests/conftest.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_polar_diffraction2d.py
  pyxem/tests/test_utils/test_big_data_utils.py
  pyxem/tests/test_utils/test_expt_utils.py
  pyxem/utils/big_data_utils.py
  pyxem/utils/expt_utils.py
Labels: enhancement

#575 bugfix for `get_nth_best_solution`
  pyxem/generators/indexation_generator.py
  pyxem/utils/indexation_utils.py
Labels: bug

#573 pyxem-0.11.0
  .gitignore
  README.rst
  pyxem/generators/calibration_generator.py
  pyxem/generators/indexation_generator.py
  pyxem/hyperspy_extension.yaml
  pyxem/release_info.py
  pyxem/signals/electron_diffraction2d.py
  pyxem/tests/test_generators/test_calibration_generator.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/utils/indexation_utils.py
  setup.py
Labels: dev
