Repository pyxem/pyxem, pull requests merged in 2020-04, with the labels that each got.

#578 Fix the link to HyperSpy developer guide
  CONTRIBUTING.rst
Labels: documentation

#582 Peak finder performance
  pyxem/release_info.py
  pyxem/tests/test_utils/test_peakfinders2D.py
  pyxem/utils/peakfinders2D.py
  setup.py
Labels: enhancement

#586 Minor bugfix for plotting vector matching results
  pyxem/release_info.py
  pyxem/signals/indexation_results.py
  pyxem/tests/test_workflows/test_orientation_mapping_phys.py
Labels: bug

#588 fix travis and black code style
  .travis.yml
  README.rst
  appveyor.yml
  pyxem/signals/common_diffraction.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/electron_diffraction2d.py
  pyxem/tests/test_signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_diffraction_variance2d.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/tests/test_utils/test_pyfai_utils.py
  pyxem/utils/pyfai_utils.py
Labels: dev

#592 Change pytest XFAIL to explicitly check correct error is raised
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/generators/vdf_generator.py
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/segments.py
  pyxem/tests/test_generators/test_calibration_generator.py
  pyxem/tests/test_generators/test_indexation_generator.py
  pyxem/tests/test_generators/test_pdf_generator.py
  pyxem/tests/test_generators/test_red_intensity_generator.py
  pyxem/tests/test_generators/test_subpixelrefinement_generator.py
  pyxem/tests/test_generators/test_vdf_generator.py
  pyxem/tests/test_library/test_calibration_library.py
  pyxem/tests/test_signals/test_crystallographic_map.py
  pyxem/tests/test_signals/test_diffraction_vectors.py
  pyxem/tests/test_signals/test_electron_diffraction2d.py
  pyxem/tests/test_signals/test_segments.py
  pyxem/tests/test_utils/test_big_data_utils.py
  pyxem/tests/test_utils/test_subpixel_utils.py
  pyxem/tests/test_utils/test_vector_utils.py
Labels: dev, enhancement
