Repository pyxem/pyxem, pull requests merged in 2020-12, with the labels that each got.

#679 Tidying up the dummy data NBD code
  pyxem/dummy_data/dummy_data.py
  pyxem/tests/dummy_data/test_dummy_data.py
Labels: needs review

#676 Tidying up the class arrangement for "ai"
  CHANGELOG.md
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
Labels: needs review

#677 Upstreaming peakfinders, tidy up for the lazy/non-lazy implementations
  CHANGELOG.md
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/signals/test_electron_diffraction2d.py
  pyxem/tests/signals/test_pixelated_stem_class.py
  pyxem/tests/utils/test_marker_tools.py
Labels: needs review

#618 FEM-Redesign
  pyxem/generators/variance_generator.py
  pyxem/signals/common_diffraction.py
  pyxem/signals/diffraction2d.py
  pyxem/tests/generators/test_calibration_generator.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/test_signals/test_metadata.py
Labels: status: stalled

#681 unduplicating correct_bad_pixel (removing remove_dead_pixel)
  CHANGELOG.md
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/signals/test_electron_diffraction2d.py
  pyxem/tests/signals/test_pixelated_stem_class.py
  pyxem/tests/utils/test_expt_utils.py
  pyxem/utils/expt_utils.py
Labels: needs review

#686 Fix bug in get_direct_beam_position: non-uniform chunks
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
Labels: bug, needs review

#683 Tidying up hot and dead pixel code
  pyxem/dummy_data/dask_test_data.py
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/signals/test_pixelated_stem_class.py
  pyxem/tests/utils/test_dask_tools.py
Labels: needs review

#668 Add lazy version of Diffraction2D.get_azimuthal_integral1d
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/utils/dask_tools.py
Labels: enhancement, status: WIP
