Repository pyxem/pyxem, pull requests merged in 2020-11, with the labels that each got.

#654 Rebuilding the orientation mapping workflow to make use of orix.CrystalMap
  .travis.yml
  pyxem/__init__.py
  pyxem/generators/indexation_generator.py
  pyxem/hyperspy_extension.yaml
  pyxem/signals/crystallographic_map.py
  pyxem/signals/indexation_results.py
  pyxem/tests/conftest.py
  pyxem/tests/generators/test_indexation_generator.py
  pyxem/tests/signals/test_crystallographic_map.py
  pyxem/tests/signals/test_indexation_results.py
  pyxem/tests/utils/test_indexation_utils.py
  pyxem/tests/utils/test_io_utils.py
  pyxem/utils/indexation_utils.py
  setup.py
Labels: breaking-change, enhancement

#658 Add lazy version of Diffraction2D.center_direct_beam
  CHANGELOG.md
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/signals/test_electron_diffraction2d.py
  pyxem/tests/utils/test_dask_tools.py
  pyxem/utils/dask_tools.py
Labels: enhancement

#665 Starting 0.12.3 release
  .github/workflows/build.yml
  .travis.yml
  CHANGELOG.md
  README.rst
  setup.py
Labels: dev, enhancement, status: WIP
