Repository pyxem/pyxem, pull requests merged in 2021-01, with the labels that each got.

#708 Gets coverage within one PR of 100%
  pyxem/generators/indexation_generator.py
  pyxem/tests/conftest.py
  pyxem/tests/generators/test_indexation_generator.py
  pyxem/tests/generators/test_virtual_image_generator.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/utils/test_peakfinders2D.py
  pyxem/tests/utils/test_radial.py
  pyxem/tests/utils/test_signal_utils.py
  pyxem/utils/cluster_tools.py
  pyxem/utils/indexation_utils.py
  pyxem/utils/peakfinder2D_gui.py
  pyxem/utils/peakfinders2D.py
Labels: dev

#707 Change default chunk size in dask_tools._get_dask_array
  pyxem/signals/diffraction2d.py
  pyxem/tests/utils/test_dask_tools.py
  pyxem/utils/dask_tools.py
Labels: enhancement, needs review

#709 Add several unit tests for utils, and remove unused functionality
  pyxem/tests/utils/test_cluster_tools.py
  pyxem/tests/utils/test_marker_tools.py
  pyxem/tests/utils/test_radial.py
  pyxem/tests/utils/test_ransac_ellipse_tools.py
  pyxem/utils/cluster_tools.py
  pyxem/utils/marker_tools.py
Labels: needs review
