Repository pyxem/pyxem, pull requests merged in 2022-04, with the labels that each got.

#822 Rephrase parts of docs and silence some warnings
  CHANGELOG.rst
  README.rst
  doc/bibliography.rst
  doc/changelog.rst
  doc/cite.rst
  doc/conf.py
  doc/contributing.rst
  doc/index.rst
  doc/open_datasets.rst
  doc/open_datasets_workflows.rst
  doc/reference.rst
  doc/related_projects.rst
Labels: documentation

#831 Update changelog: .map changes, and lazy_result change to lazy_output
  CHANGELOG.rst
Labels: needs review

#823 Removing old indexation pathway
  CHANGELOG.rst
  pyxem/generators/indexation_generator.py
  pyxem/hyperspy_extension.yaml
  pyxem/signals/__init__.py
  pyxem/signals/indexation_results.py
  pyxem/tests/generators/test_indexation_generator.py
  pyxem/tests/signals/test_indexation_results.py
  pyxem/tests/utils/test_indexation_utils.py
  pyxem/utils/indexation_utils.py
Labels: breaking-change, needs review

#839 Allow manual trigger of PyPI publish action
  .github/workflows/python-publish.yml
Labels: dev
