Repository pyxem/pyxem, pull requests merged in 2022-01, with the labels that each got.

#790 Make CI continue even after tests of docstring examples fail
  .github/workflows/build.yml
  pyxem/utils/segment_utils.py
Labels: dev

#785 Add find_diffraction_calibration
  CHANGELOG.rst
  pyxem/tests/conftest.py
  pyxem/tests/utils/test_calibration_utils.py
  pyxem/utils/calibration_utils.py
Labels: enhancement

#791 Update package credits
  pyxem/release_info.py
Labels: dev

#795 Fix skimage.draw.circle to skimage.draw.disk, circle is deprecated
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/tests/generators/test_subpixelrefinement_generator.py
Labels: bug, needs review
