Repository pyxem/pyxem, pull requests merged in 2023-01, with the labels that each got.

#845 Add center-of-mass algorithm to get_direct_beam_position
  CHANGELOG.rst
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
Labels: enhancement

#886 Center direct beam refactor
  CHANGELOG.rst
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
Labels: 0.15

#893 [maint] Addressing some small issues in the workflows
  .github/workflows/build.yml
  .github/workflows/python-publish.yml
Labels: dev, 0.15

#895 Bugfix for Strain Mapping Code
  pyxem/generators/displacement_gradient_tensor_generator.py
  pyxem/signals/diffraction_vectors.py
  pyxem/tests/generators/test_displacement_gradient_tensor_generator.py
  pyxem/tests/utils/test_expt_utils.py
  pyxem/utils/expt_utils.py
  pyxem/utils/vector_utils.py
Labels: 0.15
