Repository pyxem/pyxem, pull requests merged in 2023-11, with the labels that each got.

#935 Add nd-filtering
  CHANGELOG.rst
  examples/processing/filtering_data.py
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  setup.py
Labels: 0.16.0

#949 Expose magnitude limits to DPCSignal2D methods
  CHANGELOG.rst
  pyxem/signals/differential_phase_contrast.py
  pyxem/tests/signals/test_differential_phase_contrast.py
Labels: 0.16.0

#975 github: Add test publish workflow
  .github/workflows/test-python-publish.yml
Labels: Test Publish

#978 Add missing pooch dependency
  setup.py
Labels: dev
