Repository pyxem/pyxem, pull requests merged in 2024-02, with the labels that each got.

#1005 Center of Mass --> Map function
  CHANGELOG.rst
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_pixelated_stem_class.py
  pyxem/utils/dask_tools.py
  pyxem/utils/expt_utils.py
Labels: needs review

#1009 Azimuthal Example
  CHANGELOG.rst
  examples/processing/azimuthal_integration.py
  pyxem/signals/diffraction2d.py
  pyxem/utils/_azimuthal_utils.py
Labels: needs review

#980 Refactor Subpixel Refinement
  CHANGELOG.rst
  examples/processing/vector_finding.py
  pyxem/generators/subpixelrefinement_generator.py
  pyxem/signals/diffraction_vectors.py
  pyxem/tests/signals/test_diffraction_vectors.py
  pyxem/utils/_subpixel_utils.py
Labels: waiting on author

#1020 Tidying up the utils namespace
  pyxem/signals/diffraction2d.py
  pyxem/signals/pair_distribution_function1d.py
  pyxem/tests/utils/test_cluster_tools.py
  pyxem/tests/utils/test_dask_tools.py
  pyxem/tests/utils/test_plotting_utils.py
  pyxem/utils/__init__.py
  pyxem/utils/_background_subtraction.py
  pyxem/utils/_cluster_tools.py
  pyxem/utils/expt_utils.py
  pyxem/utils/pdf_utils.py
  pyxem/utils/plotting.py
Labels: dev

#1014 Deprecate Virtual Imaging
  CHANGELOG.rst
  examples/virtual_imaging/README.rst
  examples/virtual_imaging/creating_virtual_images_from_vectors.py
  examples/virtual_imaging/interactive_virtual_images.py
  examples/virtual_imaging/other_virtual_imaging.py
  pyxem/generators/virtual_image_generator.py
  pyxem/signals/common_diffraction.py
  pyxem/signals/diffraction_vectors2d.py
Labels: needs review

#1012 Add GPU Support
  CHANGELOG.rst
  doc/user_guide/gpu_computations.rst
  doc/user_guide/index.rst
  pyxem/__init__.py
  pyxem/signals/common_diffraction.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/polar_diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/utils/test_calibration_utils.py
  pyxem/utils/_azimuthal_utils.py
  pyxem/utils/calibration_utils.py
Labels: needs review
