Repository pyxem/pyxem, pull requests merged in 2024-03, with the labels that each got.

#1030 Deprecation of {pyfai,segment,virtual_images} utils
  CHANGELOG.rst
  pyxem/utils/pyfai_utils.py
  pyxem/utils/segment_utils.py
  pyxem/utils/virtual_images_utils.py
Labels: needs review, deletion-candidate

#1035 Renaming two private utils to drop the '_utils' suffix
  examples/virtual_imaging/creating_a_segmented_detector.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/diffraction_vectors.py
  pyxem/tests/signals/test_diffraction_vectors.py
  pyxem/utils/_azimuthal_integrations.py
  pyxem/utils/_subpixel_finding.py
  pyxem/utils/calibration_utils.py
Labels: needs review

#1034 Making more utils private (correlation_utils and pixelated_stem_tools)
  pyxem/signals/beam_shift.py
  pyxem/signals/correlation1d.py
  pyxem/signals/correlation2d.py
  pyxem/signals/differential_phase_contrast.py
  pyxem/signals/diffraction2d.py
  pyxem/signals/insitu_diffraction2d.py
  pyxem/signals/polar_diffraction2d.py
  pyxem/tests/utils/test_correlation_utils.py
  pyxem/tests/utils/test_dask_tools.py
  pyxem/tests/utils/test_dpc_signal_tools.py
  pyxem/tests/utils/test_pixelated_stem_tools.py
  pyxem/tests/utils/test_tools.py
  pyxem/utils/_correlations.py
  pyxem/utils/_pixelated_stem_tools.py
  pyxem/utils/correlation_utils.py
  pyxem/utils/radial_utils.py
Labels: status: WIP, waiting on author

#1040 Pruning utils.dask_tools as described in #1006
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.rst
  README.rst
  pyxem/signals/diffraction2d.py
  pyxem/tests/signals/test_diffraction2d.py
  pyxem/tests/utils/test_dask_tools.py
  pyxem/utils/dask_tools.py
Labels: needs review

#1024 Flatten Diffraction Vector Bugfix
  CHANGELOG.rst
  doc/dev_guide/contributing.rst
  pyxem/signals/diffraction_vectors.py
  pyxem/signals/diffraction_vectors2d.py
  pyxem/signals/labeled_diffraction_vectors2d.py
  pyxem/tests/signals/test_diffraction_vectors.py
  pyxem/tests/signals/test_diffraction_vectors2d.py
  pyxem/tests/utils/test_vector_utils.py
  pyxem/utils/_slicers.py
  pyxem/utils/ransac_ellipse_tools.py
Labels: needs review

#1047 Finishing up 1.0.0 adjustments of utils.dask_tools/_dask
  CHANGELOG.rst
  pyxem/signals/diffraction2d.py
  pyxem/signals/insitu_diffraction2d.py
  pyxem/tests/utils/test_dask_tools.py
  pyxem/utils/_dask.py
  pyxem/utils/dask_tools.py
  pyxem/utils/indexation_utils.py
  pyxem/utils/plotting_utils.py
Labels: needs review
